INSERT INTO TAB_OMIN_META_OBSVCRIT(OBSVCRITPK,STARTTIME,ENDTIME,NAMEANDVER,ISSUEORG) VALUES(:OBSVCRITPK,:STARTTIME,:ENDTIME,:NAMEANDVER,:ISSUEORG)
类型 - VARCHAR:OBSVCRITPK,STARTTIME,ENDTIME,NAMEANDVER,ISSUEORG;	

INSERT INTO TAB_OMIN_META_SUMMARY(SUMMARYPK,SUMMARYEVENTSN,STARTTIME,ENDTIME,SUMMARY_EVENT,SUMMARYEVENTID) VALUES(:SUMMARYPK,:SUMMARYEVENTSN,:STARTTIME,:ENDTIME,:SUMMARY_EVENT,:SUMMARYEVENTID)
类型 - NUMERIC:SUMMARYEVENTSN,SUMMARYEVENTID;	VARCHAR:SUMMARYPK,STARTTIME,ENDTIME,SUMMARY_EVENT;	

INSERT INTO TAB_OMIN_META_WEATHERDESC(WEATHERDESCPK,RECDTIME,FEATURE,MAJORDESC,KEYDESC,LONGADVERSEWEATHER,OVERALLEVALUATION) VALUES(:WEATHERDESCPK,:RECDTIME,:FEATURE,:MAJORDESC,:KEYDESC,:LONGADVERSEWEATHER,:OVERALLEVALUATION)
类型 - VARCHAR:WEATHERDESCPK,RECDTIME,FEATURE,MAJORDESC,KEYDESC,LONGADVERSEWEATHER,OVERALLEVALUATION;	

INSERT INTO TAB_OMIN_META_NOTEEVENT(NOTEEVENTPK,GENERALEVENTID,STARTTIME,ENDTIME,GENERALEVENTDESC,EVENTTYPE,GIFNAME,PRONAME,N_FUNCLAYER,N_CONDILAYER,N_PROVICECODE,N_CITYCODE) VALUES(:NOTEEVENTPK,:GENERALEVENTID,:STARTTIME,:ENDTIME,:GENERALEVENTDESC,:EVENTTYPE,:GIFNAME,:PRONAME,:N_FUNCLAYER,:N_CONDILAYER,:N_PROVICECODE,:N_CITYCODE)
类型 - NUMERIC:GENERALEVENTID,EVENTTYPE;	VARCHAR:NOTEEVENTPK,STARTTIME,ENDTIME,GENERALEVENTDESC,GIFNAME,PRONAME,N_FUNCLAYER,N_CONDILAYER,N_PROVICECODE,N_CITYCODE;	

INSERT INTO TAB_OMIN_META_ATTACHMENT(TABLENAME,OBJPK,ATTACHPK,ATTACHTYPE,ATTACHNAME,ATTACHDESC,CREATEDATE,UPLOADDATE,ATTACHUPDATE,UPLOADBY,EXTNAME,IMPORTSTATE) VALUES(:TABLENAME,:OBJPK,:ATTACHPK,:ATTACHTYPE,:ATTACHNAME,:ATTACHDESC,:CREATEDATE,:UPLOADDATE,:ATTACHUPDATE,:UPLOADBY,:EXTNAME,:IMPORTSTATE)
类型 - NUMERIC:ATTACHTYPE;	VARCHAR:TABLENAME,OBJPK,ATTACHPK,ATTACHNAME,ATTACHDESC,CREATEDATE,UPLOADDATE,ATTACHUPDATE,UPLOADBY,EXTNAME,IMPORTSTATE;	

INSERT INTO TAB_OMIN_META_OBSTACLE(OBSTPK,OBSTSN,OBSTCLASS,DIRECTION,ELEVANGLE,WIDTHANGLE,DISTANCE,STARTTIME,ENDTIME) VALUES(:OBSTPK,:OBSTSN,:OBSTCLASS,:DIRECTION,:ELEVANGLE,:WIDTHANGLE,:DISTANCE,:STARTTIME,:ENDTIME)
类型 - VARCHAR:OBSTPK,OBSTSN,OBSTCLASS,DIRECTION,ELEVANGLE,WIDTHANGLE,DISTANCE,STARTTIME,ENDTIME;	

INSERT INTO TAB_OMIN_META_POLLUTE(POLLUTEPK,POLLUTESN,POLLUTECLASS,DIRECTION,DISTANCE,STARTTIME,ENDTIME) VALUES(:POLLUTEPK,:POLLUTESN,:POLLUTECLASS,:DIRECTION,:DISTANCE,:STARTTIME,:ENDTIME)
类型 - VARCHAR:POLLUTEPK,POLLUTESN,POLLUTECLASS,DIRECTION,DISTANCE,STARTTIME,ENDTIME;	

INSERT INTO TAB_OMIN_META_CHGINFO(CHGINFOTYPE,CHGINFOPK,NETWORKPK,OBJPK,CHGITEMID,ITEMLINENO,CHGTAG,VALUE01,VALUE02,VALUE03,VALUE04,VALUE05,VALUE06,VALUE07,VALUE08,VALUE09,VALUE10,VALUE11,VALUE12,VALUE13,VALUE14,VALUE15,VALUE16,VALUE17,VALUE18,VALUE19,VALUE20) VALUES(:CHGINFOTYPE,:CHGINFOPK,:NETWORKPK,:OBJPK,:CHGITEMID,:ITEMLINENO,:CHGTAG,:VALUE01,:VALUE02,:VALUE03,:VALUE04,:VALUE05,:VALUE06,:VALUE07,:VALUE08,:VALUE09,:VALUE10,:VALUE11,:VALUE12,:VALUE13,:VALUE14,:VALUE15,:VALUE16,:VALUE17,:VALUE18,:VALUE19,:VALUE20)
类型 - NUMERIC:ITEMLINENO;	VARCHAR:CHGINFOTYPE,CHGINFOPK,NETWORKPK,OBJPK,CHGITEMID,CHGTAG,VALUE01,VALUE02,VALUE03,VALUE04,VALUE05,VALUE06,VALUE07,VALUE08,VALUE09,VALUE10,VALUE11,VALUE12,VALUE13,VALUE14,VALUE15,VALUE16,VALUE17,VALUE18,VALUE19,VALUE20;	

INSERT INTO TAB_OMIN_META_WKFLDEFA(WKFLAPK,WKFLNAME,WKFLPICT,WKFLVER,WKFLTYPEA,WKFLTYPEB,WKFLFUNCID,INUSE) VALUES(:WKFLAPK,:WKFLNAME,:WKFLPICT,:WKFLVER,:WKFLTYPEA,:WKFLTYPEB,:WKFLFUNCID,:INUSE)
类型 - NUMERIC:WKFLTYPEA,WKFLTYPEB,WKFLFUNCID;	VARCHAR:WKFLAPK,WKFLNAME,WKFLPICT,WKFLVER,INUSE;	

INSERT INTO TAB_OMIN_META_WKFLDEFB(WKFLBPK,WKFLSTEPB,WKFLQUEST,WKFLMESS,WKFLNEXTSTEP1,WKFLNEXTSTEP2,WKFLDEPTTYPE,WKFLSTAFFTYPE,ORGID) VALUES(:WKFLBPK,:WKFLSTEPB,:WKFLQUEST,:WKFLMESS,:WKFLNEXTSTEP1,:WKFLNEXTSTEP2,:WKFLDEPTTYPE,:WKFLSTAFFTYPE,:ORGID)
类型 - NUMERIC:WKFLSTEPB,WKFLQUEST,WKFLNEXTSTEP1,WKFLNEXTSTEP2,WKFLDEPTTYPE,WKFLSTAFFTYPE;	VARCHAR:WKFLBPK,WKFLMESS,ORGID;	

INSERT INTO TAB_OMIN_META_WKFLRUNA(WKFLRUNAPK,WKFLDESC,WKFLSTATUS,RESULT,SUGGESTION,WKFLTYPEA,WKFLTYPEB,WKFLTYPEC,SUBMITBY,SUBMITDATE,APPRBY,APPRDATE,NETWORKPK,WKFLORIGTABLE,WKFLMODITABLE,WKFLORIGRECDID,WKFLMODIRECDID,ORGID) VALUES(:WKFLRUNAPK,:WKFLDESC,:WKFLSTATUS,:RESULT,:SUGGESTION,:WKFLTYPEA,:WKFLTYPEB,:WKFLTYPEC,:SUBMITBY,:SUBMITDATE,:APPRBY,:APPRDATE,:NETWORKPK,:WKFLORIGTABLE,:WKFLMODITABLE,:WKFLORIGRECDID,:WKFLMODIRECDID,:ORGID)
类型 - NUMERIC:RESULT,WKFLTYPEA,WKFLTYPEB;	VARCHAR:WKFLRUNAPK,WKFLDESC,WKFLSTATUS,SUGGESTION,WKFLTYPEC,SUBMITBY,SUBMITDATE,APPRBY,APPRDATE,NETWORKPK,WKFLORIGTABLE,WKFLMODITABLE,WKFLORIGRECDID,WKFLMODIRECDID,ORGID;	

INSERT INTO TAB_OMIN_META_WKFLRUNB(WKFLRUNBPK,WKFLSTEPB,ORGID,USERID,WKFLQUEST,WKFLSTEPDESC,WKFLNEXTSTEP1,WKFLNEXTSTEP2,WKFLDEPTTYPE,WKFLSTAFFTYPE,WKFLDATE0,WKFLDATE1,WKFLDATE2,WKFLBSTATUS) VALUES(:WKFLRUNBPK,:WKFLSTEPB,:ORGID,:USERID,:WKFLQUEST,:WKFLSTEPDESC,:WKFLNEXTSTEP1,:WKFLNEXTSTEP2,:WKFLDEPTTYPE,:WKFLSTAFFTYPE,:WKFLDATE0,:WKFLDATE1,:WKFLDATE2,:WKFLBSTATUS)
类型 - NUMERIC:WKFLSTEPB,WKFLQUEST,WKFLNEXTSTEP1,WKFLNEXTSTEP2,WKFLDEPTTYPE,WKFLSTAFFTYPE;	VARCHAR:WKFLRUNBPK,ORGID,USERID,WKFLSTEPDESC,WKFLDATE0,WKFLDATE1,WKFLDATE2,WKFLBSTATUS;	

INSERT INTO TAB_OMIN_META_OBSVRECD(OBSVRECDPK,STARTTIME,ENDTIME,CARRIERNAME) VALUES(:OBSVRECDPK,:STARTTIME,:ENDTIME,:CARRIERNAME)
类型 - VARCHAR:OBSVRECDPK,STARTTIME,ENDTIME,CARRIERNAME;	

INSERT INTO TAB_OMIN_META_HISLOGFROM(HISLOGFROMPK,STARTTIME,ENDTIME,HISLOGDATAFROM) VALUES(:HISLOGFROMPK,:STARTTIME,:ENDTIME,:HISLOGDATAFROM)
类型 - VARCHAR:HISLOGFROMPK,STARTTIME,ENDTIME,HISLOGDATAFROM;	

INSERT INTO TAB_OMIN_MATA_DOUCUMENT(PDOCUMENT,INPUT,PROOFREAD,PRELIMINARY,AUDI,TRANSFER,STATION,PRINTER,TRANSFERDATE,MAKETIME,SONDECODE,DETECTIONCODE) VALUES(:PDOCUMENT,:INPUT,:PROOFREAD,:PRELIMINARY,:AUDI,:TRANSFER,:STATION,:PRINTER,:TRANSFERDATE,:MAKETIME,:SONDECODE,:DETECTIONCODE)
类型 - VARCHAR:PDOCUMENT,INPUT,PROOFREAD,PRELIMINARY,AUDI,TRANSFER,STATION,PRINTER,TRANSFERDATE,MAKETIME,SONDECODE,DETECTIONCODE;	

INSERT INTO TAB_OMIN_META_INSTMODEL(INSTMOPK,INSTMODEL,INSTNAME,INSTCOMP,INSTNUM,VALUE01,VALUE02) VALUES(:INSTMOPK,:INSTMODEL,:INSTNAME,:INSTCOMP,:INSTNUM,:VALUE01,:VALUE02)
类型 - VARCHAR:INSTMOPK,INSTMODEL,INSTNAME,INSTCOMP,INSTNUM,VALUE01,VALUE02;	

INSERT INTO TAB_OMIN_META_INSTRUMENTS(APPLIANCE_ID,APPLIANCE_NAME) VALUES(:APPLIANCE_ID,:APPLIANCE_NAME)
类型 - VARCHAR:APPLIANCE_ID,APPLIANCE_NAME;	

INSERT INTO TAB_OMIN_META_NETWORK_SOIL_BAK(NETWORKSOPK,DISTRTYPE,CROP,TEXTURE10,CAPACITY10,UNITWEIGHT10,WILTING_MOISTURE10,TEXTURE20,CAPACITY20,UNITWEIGHT20,WILTING_MOISTURE20,TEXTURE30,CAPACITY30,UNITWEIGHT30,WILTING_MOISTURE30,TEXTURE40,CAPACITY40,UNITWEIGHT40,WILTING_MOISTURE40,TEXTURE50,CAPACITY50,UNITWEIGHT50,WILTING_MOISTURE50,TEXTURE60,CAPACITY60,UNITWEIGHT60,WILTING_MOISTURE60,TEXTURE80,CAPACITY80,UNITWEIGHT80,WILTING_MOISTURE80,TEXTURE100,CAPACITY100,UNITWEIGHT100,WILTING_MOISTURE100,VIEWMODE10,CROPVARETYPE,RIPE,CROPVARE,CULTIVATION,VIEWMODE20,VIEWMODE30,VIEWMODE40,VIEWMODE50,VIEWMODE60,VIEWMODE80,VIEWMODE100,VIEWMODE70,VIEWMODE90,TEXTURE70,CAPACITY70,UNITWEIGHT70,WILTING_MOISTURE70,TEXTURE90,CAPACITY90,UNITWEIGHT90,WILTING_MOISTURE90,STARTTIME,ENDTIME) VALUES(:NETWORKSOPK,:DISTRTYPE,:CROP,:TEXTURE10,:CAPACITY10,:UNITWEIGHT10,:WILTING_MOISTURE10,:TEXTURE20,:CAPACITY20,:UNITWEIGHT20,:WILTING_MOISTURE20,:TEXTURE30,:CAPACITY30,:UNITWEIGHT30,:WILTING_MOISTURE30,:TEXTURE40,:CAPACITY40,:UNITWEIGHT40,:WILTING_MOISTURE40,:TEXTURE50,:CAPACITY50,:UNITWEIGHT50,:WILTING_MOISTURE50,:TEXTURE60,:CAPACITY60,:UNITWEIGHT60,:WILTING_MOISTURE60,:TEXTURE80,:CAPACITY80,:UNITWEIGHT80,:WILTING_MOISTURE80,:TEXTURE100,:CAPACITY100,:UNITWEIGHT100,:WILTING_MOISTURE100,:VIEWMODE10,:CROPVARETYPE,:RIPE,:CROPVARE,:CULTIVATION,:VIEWMODE20,:VIEWMODE30,:VIEWMODE40,:VIEWMODE50,:VIEWMODE60,:VIEWMODE80,:VIEWMODE100,:VIEWMODE70,:VIEWMODE90,:TEXTURE70,:CAPACITY70,:UNITWEIGHT70,:WILTING_MOISTURE70,:TEXTURE90,:CAPACITY90,:UNITWEIGHT90,:WILTING_MOISTURE90,:STARTTIME,:ENDTIME)
类型 - VARCHAR:NETWORKSOPK,DISTRTYPE,CROP,TEXTURE10,CAPACITY10,UNITWEIGHT10,WILTING_MOISTURE10,TEXTURE20,CAPACITY20,UNITWEIGHT20,WILTING_MOISTURE20,TEXTURE30,CAPACITY30,UNITWEIGHT30,WILTING_MOISTURE30,TEXTURE40,CAPACITY40,UNITWEIGHT40,WILTING_MOISTURE40,TEXTURE50,CAPACITY50,UNITWEIGHT50,WILTING_MOISTURE50,TEXTURE60,CAPACITY60,UNITWEIGHT60,WILTING_MOISTURE60,TEXTURE80,CAPACITY80,UNITWEIGHT80,WILTING_MOISTURE80,TEXTURE100,CAPACITY100,UNITWEIGHT100,WILTING_MOISTURE100,VIEWMODE10,CROPVARETYPE,RIPE,CROPVARE,CULTIVATION,VIEWMODE20,VIEWMODE30,VIEWMODE40,VIEWMODE50,VIEWMODE60,VIEWMODE80,VIEWMODE100,VIEWMODE70,VIEWMODE90,TEXTURE70,CAPACITY70,UNITWEIGHT70,WILTING_MOISTURE70,TEXTURE90,CAPACITY90,UNITWEIGHT90,WILTING_MOISTURE90,STARTTIME,ENDTIME;	

INSERT INTO TAB_OMIN_META_YEAR_CLIMATE(C_ID,STATION_ID,C_TIME,C_MAIN,C_ABNORMAL,C_DAMAGE,C_CONTINUED,C_SYNTHETICAL) VALUES(:C_ID,:STATION_ID,:C_TIME,:C_MAIN,:C_ABNORMAL,:C_DAMAGE,:C_CONTINUED,:C_SYNTHETICAL)
类型 - NUMERIC:C_ID;	VARCHAR:STATION_ID,C_TIME,C_MAIN,C_ABNORMAL,C_DAMAGE,C_CONTINUED,C_SYNTHETICAL;	

INSERT INTO TAB_OMIN_META_YEAR_INSTRUMENTS(I_ID,STATION_ID,APPLIANCE_ID,APPLIANCE_NAME,I_FACTORY,I_TIME,I_MODELS,I_NUMBERS,N_TIME) VALUES(:I_ID,:STATION_ID,:APPLIANCE_ID,:APPLIANCE_NAME,:I_FACTORY,:I_TIME,:I_MODELS,:I_NUMBERS,:N_TIME)
类型 - NUMERIC:I_ID;	VARCHAR:STATION_ID,APPLIANCE_ID,APPLIANCE_NAME,I_FACTORY,I_TIME,I_MODELS,I_NUMBERS,N_TIME;	

INSERT INTO TAB_OMIN_META_YEAR_REMARK(R_ID,STATION_ID,R_TIME,R_CONTENT) VALUES(:R_ID,:STATION_ID,:R_TIME,:R_CONTENT)
类型 - NUMERIC:R_ID;	VARCHAR:STATION_ID,R_TIME,R_CONTENT;	

INSERT INTO TAB_OMIN_META_REVIEWED(RD_ID,HANDLE_TYPE,PROCESS_STATE,HANDLE_CONTENT,SUBMITTER,SUBMIT_TIME,APPROVER,APPROVAL_TIME,VALUE01,VALUE02,VALUE03,VALUE04,VALUE05,VALUE06,VALUE07,VALUE08,VALUE09,VALUE10,VALUE11,VALUE12,VALUE13,VALUE14,VALUE15,PROCESS) VALUES(:RD_ID,:HANDLE_TYPE,:PROCESS_STATE,:HANDLE_CONTENT,:SUBMITTER,:SUBMIT_TIME,:APPROVER,:APPROVAL_TIME,:VALUE01,:VALUE02,:VALUE03,:VALUE04,:VALUE05,:VALUE06,:VALUE07,:VALUE08,:VALUE09,:VALUE10,:VALUE11,:VALUE12,:VALUE13,:VALUE14,:VALUE15,:PROCESS)
类型 - NUMERIC:RD_ID;	LONGTEXT:PROCESS;	VARCHAR:HANDLE_TYPE,PROCESS_STATE,HANDLE_CONTENT,SUBMITTER,SUBMIT_TIME,APPROVER,APPROVAL_TIME;	TEXT:VALUE01,VALUE02,VALUE03,VALUE04,VALUE05,VALUE06,VALUE07,VALUE08,VALUE09,VALUE10,VALUE11,VALUE12,VALUE13,VALUE14,VALUE15;	

INSERT INTO TAB_OMIN_META_SOFT(SOFTPK,STARTTIME,ENDTIME,SOFTNAME,SOFTVER,SOFTCORP) VALUES(:SOFTPK,:STARTTIME,:ENDTIME,:SOFTNAME,:SOFTVER,:SOFTCORP)
类型 - VARCHAR:SOFTPK,STARTTIME,ENDTIME,SOFTNAME,SOFTVER,SOFTCORP;	

