SELECT
	TAB_OMIN_META_OBSVCRIT.OBSVCRITPK,TAB_OMIN_META_OBSVCRIT.STARTTIME,TAB_OMIN_META_OBSVCRIT.ENDTIME,TAB_OMIN_META_OBSVCRIT.NAMEANDVER,TAB_OMIN_META_OBSVCRIT.ISSUEORG
FROM TAB_OMIN_META_OBSVCRIT,TAB_OMIN_META_NETWORK
WHERE TAB_OMIN_META_NETWORK.NETWORKPK = SUBSTR(TAB_OMIN_META_OBSVCRIT.OBSVCRITPK,0,36) AND TAB_OMIN_META_NETWORK.Networktype in ('01','04','11','13','16','17')

SELECT
	TAB_OMIN_META_SUMMARY.SUMMARYPK,TAB_OMIN_META_SUMMARY.SUMMARYEVENTSN,TAB_OMIN_META_SUMMARY.STARTTIME,TAB_OMIN_META_SUMMARY.ENDTIME,TAB_OMIN_META_SUMMARY.SUMMARY_EVENT,TAB_OMIN_META_SUMMARY.SUMMARYEVENTID
FROM TAB_OMIN_META_SUMMARY,TAB_OMIN_META_NETWORK
WHERE SUBSTR(TAB_OMIN_META_SUMMARY.SUMMARYPK,0,36) = TAB_OMIN_META_NETWORK.NETWORKPK AND TAB_OMIN_META_NETWORK.Networktype in ('01','04','11','13','16','17')

SELECT
	TAB_OMIN_META_WEATHERDESC.WEATHERDESCPK,TAB_OMIN_META_WEATHERDESC.RECDTIME,TAB_OMIN_META_WEATHERDESC.FEATURE,TAB_OMIN_META_WEATHERDESC.MAJORDESC,TAB_OMIN_META_WEATHERDESC.KEYDESC,TAB_OMIN_META_WEATHERDESC.LONGADVERSEWEATHER,TAB_OMIN_META_WEATHERDESC.OVERALLEVALUATION
FROM TAB_OMIN_META_WEATHERDESC,TAB_OMIN_META_NETWORK
WHERE SUBSTR(TAB_OMIN_META_WEATHERDESC.WEATHERDESCPK,0,36) = TAB_OMIN_META_NETWORK.NETWORKPK AND TAB_OMIN_META_NETWORK.Networktype in ('01','04','11','13','16','17')

SELECT
	TAB_OMIN_META_NOTEEVENT.NOTEEVENTPK,TAB_OMIN_META_NOTEEVENT.GENERALEVENTID,TAB_OMIN_META_NOTEEVENT.STARTTIME,TAB_OMIN_META_NOTEEVENT.ENDTIME,TAB_OMIN_META_NOTEEVENT.GENERALEVENTDESC,TAB_OMIN_META_NOTEEVENT.EVENTTYPE,TAB_OMIN_META_NOTEEVENT.GIFNAME,TAB_OMIN_META_NOTEEVENT.PRONAME,TAB_OMIN_META_NOTEEVENT.N_FUNCLAYER,TAB_OMIN_META_NOTEEVENT.N_CONDILAYER,TAB_OMIN_META_NOTEEVENT.N_PROVICECODE,TAB_OMIN_META_NOTEEVENT.N_CITYCODE
FROM TAB_OMIN_META_NOTEEVENT,TAB_OMIN_META_NETWORK
WHERE SUBSTR(TAB_OMIN_META_NOTEEVENT.NOTEEVENTPK,0,36) = TAB_OMIN_META_NETWORK.NETWORKPK AND TAB_OMIN_META_NETWORK.Networktype in ('01','04','11','13','16','17')

SELECT
	TABLENAME,OBJPK,ATTACHPK,ATTACHTYPE,ATTACHNAME,ATTACHDESC,CREATEDATE,UPLOADDATE,ATTACHUPDATE,UPLOADBY,EXTNAME,IMPORTSTATE
FROM TAB_OMIN_META_ATTACHMENT

SELECT
	TAB_OMIN_META_OBSTACLE.OBSTPK,TAB_OMIN_META_OBSTACLE.OBSTSN,TAB_OMIN_META_OBSTACLE.OBSTCLASS,TAB_OMIN_META_OBSTACLE.DIRECTION,TAB_OMIN_META_OBSTACLE.ELEVANGLE,TAB_OMIN_META_OBSTACLE.WIDTHANGLE,TAB_OMIN_META_OBSTACLE.DISTANCE,TAB_OMIN_META_OBSTACLE.STARTTIME,TAB_OMIN_META_OBSTACLE.ENDTIME
FROM TAB_OMIN_META_OBSTACLE,TAB_OMIN_META_NETWORK
WHERE SUBSTR(TAB_OMIN_META_OBSTACLE.OBSTPK,0,36) = TAB_OMIN_META_NETWORK.NETWORKPK  AND TAB_OMIN_META_NETWORK.Networktype in ('01','04','11','13','16','17')

SELECT
	TAB_OMIN_META_POLLUTE.POLLUTEPK,TAB_OMIN_META_POLLUTE.POLLUTESN,TAB_OMIN_META_POLLUTE.POLLUTECLASS,TAB_OMIN_META_POLLUTE.DIRECTION,TAB_OMIN_META_POLLUTE.DISTANCE,TAB_OMIN_META_POLLUTE.STARTTIME,TAB_OMIN_META_POLLUTE.ENDTIME
FROM TAB_OMIN_META_POLLUTE,TAB_OMIN_META_NETWORK
WHERE SUBSTR(TAB_OMIN_META_POLLUTE.POLLUTEPK,0,36) = TAB_OMIN_META_NETWORK.NETWORKPK AND TAB_OMIN_META_NETWORK.Networktype in ('01','04','11','13','16','17')

SELECT
	TAB_OMIN_META_CHGINFO.CHGINFOTYPE,TAB_OMIN_META_CHGINFO.CHGINFOPK,TAB_OMIN_META_CHGINFO.NETWORKPK,TAB_OMIN_META_CHGINFO.OBJPK,TAB_OMIN_META_CHGINFO.CHGITEMID,TAB_OMIN_META_CHGINFO.ITEMLINENO,TAB_OMIN_META_CHGINFO.CHGTAG,TAB_OMIN_META_CHGINFO.VALUE01,TAB_OMIN_META_CHGINFO.VALUE02,TAB_OMIN_META_CHGINFO.VALUE03,TAB_OMIN_META_CHGINFO.VALUE04,TAB_OMIN_META_CHGINFO.VALUE05,TAB_OMIN_META_CHGINFO.VALUE06,TAB_OMIN_META_CHGINFO.VALUE07,TAB_OMIN_META_CHGINFO.VALUE08,TAB_OMIN_META_CHGINFO.VALUE09,TAB_OMIN_META_CHGINFO.VALUE10,TAB_OMIN_META_CHGINFO.VALUE11,TAB_OMIN_META_CHGINFO.VALUE12,TAB_OMIN_META_CHGINFO.VALUE13,TAB_OMIN_META_CHGINFO.VALUE14,TAB_OMIN_META_CHGINFO.VALUE15,TAB_OMIN_META_CHGINFO.VALUE16,TAB_OMIN_META_CHGINFO.VALUE17,TAB_OMIN_META_CHGINFO.VALUE18,TAB_OMIN_META_CHGINFO.VALUE19,TAB_OMIN_META_CHGINFO.VALUE20
FROM TAB_OMIN_META_CHGINFO,TAB_OMIN_CM_CC_STATION,TAB_OMIN_META_NETWORK
WHERE TAB_OMIN_META_CHGINFO.CHGINFOTYPE='1' AND TAB_OMIN_CM_CC_STATION.C_STATION_ID = SUBSTR(TAB_OMIN_META_CHGINFO.NETWORKPK,0,32) AND TAB_OMIN_META_NETWORK.NETWORKPK = TAB_OMIN_META_CHGINFO.NETWORKPK AND TAB_OMIN_META_NETWORK.Networktype in ('01','04','11','13','16','17')

SELECT
	WKFLAPK,WKFLNAME,WKFLPICT,WKFLVER,WKFLTYPEA,WKFLTYPEB,WKFLFUNCID,INUSE
FROM TAB_OMIN_META_WKFLDEFA

SELECT
	WKFLBPK,WKFLSTEPB,WKFLQUEST,WKFLMESS,WKFLNEXTSTEP1,WKFLNEXTSTEP2,WKFLDEPTTYPE,WKFLSTAFFTYPE,ORGID
FROM TAB_OMIN_META_WKFLDEFB

-- SELECT
-- 	WKFLRUNAPK,WKFLDESC,WKFLSTATUS,RESULT,SUGGESTION,WKFLTYPEA,WKFLTYPEB,WKFLTYPEC,SUBMITBY,SUBMITDATE,APPRBY,APPRDATE,NETWORKPK,WKFLORIGTABLE,WKFLMODITABLE,WKFLORIGRECDID,WKFLMODIRECDID,ORGID
-- FROM TAB_OMIN_META_WKFLRUNA

-- SELECT
-- 	WKFLRUNBPK,WKFLSTEPB,ORGID,USERID,WKFLQUEST,WKFLSTEPDESC,WKFLNEXTSTEP1,WKFLNEXTSTEP2,WKFLDEPTTYPE,WKFLSTAFFTYPE,WKFLDATE0,WKFLDATE1,WKFLDATE2,WKFLBSTATUS
-- FROM TAB_OMIN_META_WKFLRUNB

SELECT
	TAB_OMIN_META_OBSVRECD.OBSVRECDPK,TAB_OMIN_META_OBSVRECD.STARTTIME,TAB_OMIN_META_OBSVRECD.ENDTIME,TAB_OMIN_META_OBSVRECD.CARRIERNAME
FROM TAB_OMIN_META_OBSVRECD,TAB_OMIN_META_NETWORK
WHERE TAB_OMIN_META_NETWORK.NETWORKPK = SUBSTR(TAB_OMIN_META_OBSVRECD.OBSVRECDPK,0,36) AND TAB_OMIN_META_NETWORK.Networktype in ('01','04','11','13','16','17')

SELECT
	TAB_OMIN_META_HISLOGFROM.HISLOGFROMPK,TAB_OMIN_META_HISLOGFROM.STARTTIME,TAB_OMIN_META_HISLOGFROM.ENDTIME,TAB_OMIN_META_HISLOGFROM.HISLOGDATAFROM
FROM TAB_OMIN_META_HISLOGFROM,TAB_OMIN_META_NETWORK
WHERE TAB_OMIN_META_NETWORK.NETWORKPK = SUBSTR(TAB_OMIN_META_HISLOGFROM.HISLOGDATAFROM,0,36) AND TAB_OMIN_META_NETWORK.Networktype in ('01','04','11','13','16','17')

SELECT
	PDOCUMENT,INPUT,PROOFREAD,PRELIMINARY,AUDI,TRANSFER,STATION,PRINTER,TRANSFERDATE,MAKETIME,SONDECODE,DETECTIONCODE
FROM TAB_OMIN_MATA_DOUCUMENT

SELECT
	INSTMOPK,INSTMODEL,INSTNAME,INSTCOMP,INSTNUM,VALUE01,VALUE02
FROM TAB_OMIN_META_INSTMODEL

SELECT
	APPLIANCE_ID,APPLIANCE_NAME
FROM TAB_OMIN_META_INSTRUMENTS

SELECT
	NETWORKSOPK,DISTRTYPE,CROP,TEXTURE10,CAPACITY10,UNITWEIGHT10,WILTING_MOISTURE10,TEXTURE20,CAPACITY20,UNITWEIGHT20,WILTING_MOISTURE20,TEXTURE30,CAPACITY30,UNITWEIGHT30,WILTING_MOISTURE30,TEXTURE40,CAPACITY40,UNITWEIGHT40,WILTING_MOISTURE40,TEXTURE50,CAPACITY50,UNITWEIGHT50,WILTING_MOISTURE50,TEXTURE60,CAPACITY60,UNITWEIGHT60,WILTING_MOISTURE60,TEXTURE80,CAPACITY80,UNITWEIGHT80,WILTING_MOISTURE80,TEXTURE100,CAPACITY100,UNITWEIGHT100,WILTING_MOISTURE100,VIEWMODE10,CROPVARETYPE,RIPE,CROPVARE,CULTIVATION,VIEWMODE20,VIEWMODE30,VIEWMODE40,VIEWMODE50,VIEWMODE60,VIEWMODE80,VIEWMODE100,VIEWMODE70,VIEWMODE90,TEXTURE70,CAPACITY70,UNITWEIGHT70,WILTING_MOISTURE70,TEXTURE90,CAPACITY90,UNITWEIGHT90,WILTING_MOISTURE90,STARTTIME,ENDTIME
FROM TAB_OMIN_META_NETWORK_SOIL_BAK

SELECT
	C_ID,STATION_ID,C_TIME,C_MAIN,C_ABNORMAL,C_DAMAGE,C_CONTINUED,C_SYNTHETICAL
FROM TAB_OMIN_META_YEAR_CLIMATE

SELECT
	I_ID,STATION_ID,APPLIANCE_ID,APPLIANCE_NAME,I_FACTORY,I_TIME,I_MODELS,I_NUMBERS,N_TIME
FROM TAB_OMIN_META_YEAR_INSTRUMENTS

SELECT
	R_ID,STATION_ID,R_TIME,R_CONTENT
FROM TAB_OMIN_META_YEAR_REMARK

-- SELECT
-- 	RD_ID,HANDLE_TYPE,PROCESS_STATE,HANDLE_CONTENT,SUBMITTER,SUBMIT_TIME,APPROVER,APPROVAL_TIME,VALUE01,VALUE02,VALUE03,VALUE04,VALUE05,VALUE06,VALUE07,VALUE08,VALUE09,VALUE10,VALUE11,VALUE12,VALUE13,VALUE14,VALUE15,PROCESS
-- FROM TAB_OMIN_META_REVIEWED

SELECT
	SOFTPK,STARTTIME,ENDTIME,SOFTNAME,SOFTVER,SOFTCORP
FROM TAB_OMIN_META_SOFT

