SELECT
	OBSVCRITPK,STARTTIME,ENDTIME,NAMEANDVER,ISSUEORG
FROM TAB_OMIN_META_OBSVCRIT

SELECT
	SUMMARYPK,SUMMARYEVENTSN,STARTTIME,ENDTIME,SUMMARY_EVENT,SUMMARYEVENTID
FROM TAB_OMIN_META_SUMMARY

SELECT
	WEATHERDESCPK,RECDTIME,FEATURE,MAJORDESC,KEYDESC,LONGADVERSEWEATHER,OVERALLEVALUATION
FROM TAB_OMIN_META_WEATHERDESC

SELECT
	NOTEEVENTPK,GENERALEVENTID,STARTTIME,ENDTIME,GENERALEVENTDESC,EVENTTYPE,GIFNAME,PRONAME,N_FUNCLAYER,N_CONDILAYER,N_PROVICECODE,N_CITYCODE
FROM TAB_OMIN_META_NOTEEVENT

SELECT
	TABLENAME,OBJPK,ATTACHPK,ATTACHTYPE,ATTACHNAME,ATTACHDESC,CREATEDATE,UPLOADDATE,ATTACHUPDATE,UPLOADBY,EXTNAME,IMPORTSTATE
FROM TAB_OMIN_META_ATTACHMENT

SELECT
	OBSTPK,OBSTSN,OBSTCLASS,DIRECTION,ELEVANGLE,WIDTHANGLE,DISTANCE,STARTTIME,ENDTIME
FROM TAB_OMIN_META_OBSTACLE

SELECT
	POLLUTEPK,POLLUTESN,POLLUTECLASS,DIRECTION,DISTANCE,STARTTIME,ENDTIME
FROM TAB_OMIN_META_POLLUTE

SELECT
	CHGINFOTYPE,CHGINFOPK,NETWORKPK,OBJPK,CHGITEMID,ITEMLINENO,CHGTAG,TAB_OMIN_META_NETWORK.NETWORKTYPE AS NETWORKTYPE,VALUE01,VALUE02,VALUE03,VALUE04,VALUE05,VALUE06,VALUE07,VALUE08,VALUE09,VALUE10,VALUE11,VALUE12,VALUE13,VALUE14,VALUE15,VALUE16,VALUE17,VALUE18,VALUE19,VALUE20
FROM TAB_OMIN_META_CHGINFO,TAB_OMIN_CM_CC_STATION,TAB_OMIN_META_NETWORK
WHERE TAB_OMIN_META_CHGINFO.CHGINFOTYPE='1' AND TAB_OMIN_CM_CC_STATION.C_STATION_ID = SUBSTR(TAB_OMIN_META_CHGINFO.NETWORKPK(+),0,32) AND TAB_OMIN_META_NETWORK.NETWORKPK = TAB_OMIN_META_CHGINFO.NETWORKPK

SELECT
	WKFLAPK,WKFLNAME,WKFLPICT,WKFLVER,WKFLTYPEA,WKFLTYPEB,WKFLFUNCID,INUSE
FROM TAB_OMIN_META_WKFLDEFA

SELECT
	WKFLBPK,WKFLSTEPB,WKFLQUEST,WKFLMESS,WKFLNEXTSTEP1,WKFLNEXTSTEP2,WKFLDEPTTYPE,WKFLSTAFFTYPE,ORGID
FROM TAB_OMIN_META_WKFLDEFB

-- SELECT
-- 	WKFLRUNAPK,WKFLDESC,WKFLSTATUS,RESULT,SUGGESTION,WKFLTYPEA,WKFLTYPEB,WKFLTYPEC,SUBMITBY,SUBMITDATE,APPRBY,APPRDATE,NETWORKPK,WKFLORIGTABLE,WKFLMODITABLE,WKFLORIGRECDID,WKFLMODIRECDID,ORGID
-- FROM TAB_OMIN_META_WKFLRUNA

-- SELECT
-- 	WKFLRUNBPK,WKFLSTEPB,ORGID,USERID,WKFLQUEST,WKFLSTEPDESC,WKFLNEXTSTEP1,WKFLNEXTSTEP2,WKFLDEPTTYPE,WKFLSTAFFTYPE,WKFLDATE0,WKFLDATE1,WKFLDATE2,WKFLBSTATUS
-- FROM TAB_OMIN_META_WKFLRUNB

SELECT
	OBSVRECDPK,STARTTIME,ENDTIME,CARRIERNAME
FROM TAB_OMIN_META_OBSVRECD

SELECT
	HISLOGFROMPK,STARTTIME,ENDTIME,HISLOGDATAFROM
FROM TAB_OMIN_META_HISLOGFROM

SELECT
	PDOCUMENT,INPUT,PROOFREAD,PRELIMINARY,AUDI,TRANSFER,STATION,PRINTER,TRANSFERDATE,MAKETIME,SONDECODE,DETECTIONCODE
FROM TAB_OMIN_MATA_DOUCUMENT

SELECT
	INSTMOPK,INSTMODEL,INSTNAME,INSTCOMP,INSTNUM,VALUE01,VALUE02
FROM TAB_OMIN_META_INSTMODEL

SELECT
	APPLIANCE_ID,APPLIANCE_NAME
FROM TAB_OMIN_META_INSTRUMENTS

SELECT
	NETWORKSOPK,DISTRTYPE,CROP,TEXTURE10,CAPACITY10,UNITWEIGHT10,WILTING_MOISTURE10,TEXTURE20,CAPACITY20,UNITWEIGHT20,WILTING_MOISTURE20,TEXTURE30,CAPACITY30,UNITWEIGHT30,WILTING_MOISTURE30,TEXTURE40,CAPACITY40,UNITWEIGHT40,WILTING_MOISTURE40,TEXTURE50,CAPACITY50,UNITWEIGHT50,WILTING_MOISTURE50,TEXTURE60,CAPACITY60,UNITWEIGHT60,WILTING_MOISTURE60,TEXTURE80,CAPACITY80,UNITWEIGHT80,WILTING_MOISTURE80,TEXTURE100,CAPACITY100,UNITWEIGHT100,WILTING_MOISTURE100,VIEWMODE10,CROPVARETYPE,RIPE,CROPVARE,CULTIVATION,VIEWMODE20,VIEWMODE30,VIEWMODE40,VIEWMODE50,VIEWMODE60,VIEWMODE80,VIEWMODE100,VIEWMODE70,VIEWMODE90,TEXTURE70,CAPACITY70,UNITWEIGHT70,WILTING_MOISTURE70,TEXTURE90,CAPACITY90,UNITWEIGHT90,WILTING_MOISTURE90,STARTTIME,ENDTIME
FROM TAB_OMIN_META_NETWORK_SOIL_BAK

SELECT
	C_ID,STATION_ID,C_TIME,C_MAIN,C_ABNORMAL,C_DAMAGE,C_CONTINUED,C_SYNTHETICAL
FROM TAB_OMIN_META_YEAR_CLIMATE

SELECT
	I_ID,STATION_ID,APPLIANCE_ID,APPLIANCE_NAME,I_FACTORY,I_TIME,I_MODELS,I_NUMBERS,N_TIME
FROM TAB_OMIN_META_YEAR_INSTRUMENTS

SELECT
	R_ID,STATION_ID,R_TIME,R_CONTENT
FROM TAB_OMIN_META_YEAR_REMARK

-- SELECT
-- 	RD_ID,HANDLE_TYPE,PROCESS_STATE,HANDLE_CONTENT,SUBMITTER,SUBMIT_TIME,APPROVER,APPROVAL_TIME,VALUE01,VALUE02,VALUE03,VALUE04,VALUE05,VALUE06,VALUE07,VALUE08,VALUE09,VALUE10,VALUE11,VALUE12,VALUE13,VALUE14,VALUE15,PROCESS
-- FROM TAB_OMIN_META_REVIEWED

SELECT
	SOFTPK,STARTTIME,ENDTIME,SOFTNAME,SOFTVER,SOFTCORP
FROM TAB_OMIN_META_SOFT

