SELECT
  TAB_OMIN_META_NETWORK.NETWORKPK as C_SITEOPF_ID,TAB_OMIN_META_NETWORK.NetWorkLevel as C_STATION_LEVEL,
  TAB_OMIN_CM_CC_STATION.c_estadate as C_StartTime,
  TAB_OMIN_META_NETWORK.StartTime as C_netstarttime,TAB_OMIN_META_NETWORK.EndTime as C_netEndTime,TAB_OMIN_META_NETWORK.TimeSystem as C_TimeSystem,TAB_OMIN_META_NETWORK.ObsvCount as C_ObsvCount,TAB_OMIN_META_NETWORK.ObsvTimes as C_ObsvTimes,TAB_OMIN_META_NETWORK.ExchangeCode as C_ExchangeCode,TAB_OMIN_META_NETWORK.ObsvMode as C_ObsvMode,TAB_OMIN_META_NETWORK.ShiftCase as C_ONDUTY,TAB_OMIN_META_NETWORK.HisLogDataFrom as C_HisLogDataFrom,TAB_OMIN_META_NETWORK.HisLogCompBy as C_HisLogCompBy,TAB_OMIN_META_NETWORK.HisLogAudtBy as C_HisLogAudtBy,TAB_OMIN_META_NETWORK.HISLOGCOMPDATE as C_HISLOGCOMPDATE,
  TAB_OMIN_META_REGSTATION.AUTOSTATIONMODEL as C_INSTR_MODEL,TAB_OMIN_META_REGSTATION.AUTOSTATIONMANU as C_MF,TAB_OMIN_META_REGSTATION.POWERSUPPLYMODE as C_POWER_TYPE,TAB_OMIN_META_REGSTATION.INSTALPOSITION as C_INSTALL_POS,
  -- TAB_OMIN_META_OBSVELMT.自己降水SwitchDate as C_RAIN_STIME,TAB_OMIN_META_OBSVELMT.自己降水SWITCHDATE as C_RAIN_ETIME,TAB_OMIN_META_OBSVELMT.大型蒸发量的SWITCHDATE as C_SWITCH_SDATE,TAB_OMIN_META_OBSVELMT.大型蒸发量SWITCHDATE as C_SWITCH_EDTE
  (select switchdate from TAB_OMIN_META_OBSVELMT o
    where substr(o.OBSVELMTPK,0,36) = TAB_OMIN_META_NETWORK.NETWORKPK) as switchdaterain,
  (select switchdate from tab_omin_meta_obsvelmt o2
    where substr(o2.OBSVELMTPK,0,36) = TAB_OMIN_META_NETWORK.NETWORKPK) as switchdatebig
FROM TAB_OMIN_META_NETWORK,TAB_OMIN_CM_CC_STATION,TAB_OMIN_META_REGSTATION,TAB_OMIN_META_OBSVELMT
WHERE substr(TAB_OMIN_META_NETWORK.NETWORKPK,0,32) = TAB_OMIN_CM_CC_STATION.C_STATION_ID(+) and
      TAB_OMIN_META_REGSTATION.REGSTATIONID(+) = TAB_OMIN_CM_CC_STATION.C_STATION_ID and
      SUBSTR(TAB_OMIN_META_OBSVELMT.OBSVELMTPK(+),0,36) = TAB_OMIN_META_NETWORK.NETWORKPK
      AND TAB_OMIN_META_NETWORK.NETWORKTYPE='01';